### ISSUE TITLE
Rabbitmq cluster as a docker container

### ISSUE THREAD

**Issue by vibinm** [sujiar37/AWX-HA-InstanceGroup#14]
At the moment, the rabbitmq is deployed as an RPM installation. Can we have it thru docker containers ?

By that way, we can have a fully containerized AWX application and easy to deploy in K8s or in openshift.

Regards,
Vibin

**Comment by sujiar37** [comment]
Hi @vibinm ,

Will need to see how much code refactoring is required for these changes. I would like to keep this as an optional enhancement and let the people can decide whether they require container / hosted rabbitmq solution.

**Comment by tdavison784** [comment]
I would also be interested in this solution. @sujiar37 could I kindly fork this branch and see what would need to be done to incorporate a rabbitMQ cluster and have it as an inventory flag.

**Comment by sujiar37** [comment]
Hey @tdavison784 , that's awesome. Please proceed with that 👍
