### ISSUE TITLE
Error when using SCM type - Manual

### ISSUE THREAD

**Issue by vibinm** [sujiar37/AWX-HA-InstanceGroup#15]
**Describe the bug**
Not able to use SCM type - "manual" in projects. Throws error stating the directory is empty or ......
Looks like the directory is not getting created on the containers and mapped to the docker host.

**To Reproduce**
Default install and try to configure SCM type manual in a demo project

**Expected behavior**
Should be able to select SCM type manual and map the local playbook directory

**Additional context**

**Comment by sujiar37** [comment]
Hi @vibinm ,

Thanks for reporting this. Will check and get it fixed in the upcoming release with the AWX version 9.0.0. I will keep this open at the moment.
