### ISSUE TITLE
Few generic queries...

### ISSUE THREAD

**Issue by Sreenadh8** [sujiar37/AWX-HA-InstanceGroup#16]
Hi Sujith,

Thank you for sharing this project, have been looking for promising HA setup solution, looks found one, I am new to awx so having few queries before getting into the HA setup. I'm currently using one node isolated machine which connects external PostgreSQL RDS with multi-az setup.

1) Does this HA setup has any issues connecting with external AWS RDS ?
2) AWX project will be keep upgrading the major versions very often, how easy to upgrade those major version within HA nodes without losing the existing configurations? What are the steps or efforts needed here ? appreciates if you elaborate more on what we need to do upgrade the latest versions.
3) Does this HA setup supports Application LB to load the Web interface traffic ?
4) most often we see, web interface is little sluggish for isolated AWX node in my current scenario, does this HA setup improves the web GUI response for some extent?

 Sorry if these queries might look very generic and simple,these FAQ might help beginners like me.. thank you very for much..

Regards,
Sreenadh

**Comment by sujiar37** [comment]
Thank you for your kind words @Sreenadh8 . It is all about a community effort to make things better. With regards to your questions,

1. Nope, as long as it can connect to the DB through a public/private endpoints.

2. We don't guarantee successful upgrades , if you wish to explore more related with that there is a RPM version of AWX by other community with very strong support and guidance.
[MrMEE](https://github.com/MrMEEE) - [AWX_RPM](https://github.com/MrMEEE/awx-build)

But still, you have few options to explore manual migration between version upgrades via [awx-cli/tower-cli](https://github.com/ansible/tower-cli)

3. Yes , it is. All the configured nodes are acts as a Primary-Primary replica with a common DB. Hence, you could easily load balance via a virtual ip with a proper routing.

4. For any issues/improvements related with AWX, I would appreciate you to contact with the official [AWX-Community](https://github.com/ansible/awx) seek guidance. Here we simply enabling HA functionality by referring with the official AWX docker images.
