### ISSUE TITLE
no projects directory under /var/lib/awx

### ISSUE THREAD

**Issue by pavind87** [sujiar37/AWX-HA-InstanceGroup#18]
even with version 9.0.1, after the playbook completion no projects directory created under /var/lib/awx.

**Comment by sujiar37** [comment]
@pavind87 , you may have to create directories under `~/.awx/projects` in your host machines and try SCM manual operation again. 

Here is the respective bind mount regarding the same,

https://github.com/sujiar37/AWX-HA-InstanceGroup/blob/3ab37a91ca72c68619e66dc977eae801795639b2/roles/awx_ha/templates/docker-compose.yml.j2#L13-L14
