### ISSUE TITLE
Issues with pulling projects down SCM after running AWX-HA and putting hosts in instance group

### ISSUE THREAD

**Issue by AechLyons** [sujiar37/AWX-HA-InstanceGroup#19]
**Describe the bug**
After installing AWX on individual hosts (that share an external PGDB) everything works fine.  When I run the AWX-HA plays (I turned off the containers because it would complete without errors otherwise) and the AWX-HA play completes fine.  Adds a awx_web and awx_task to docker (as well as memcached i believe).  I manually restart RabbitMQ (not sure if its needed).  I was kinda working the first time but projects were slow to update (I have my templates flagged to download the latest code on every run) after some weirdness with NGINX (Itried ot also setup load balancing......I think I was doing too much) I decided to reinstall everything (deleting all containers and rerunning the plays for awx (on both hosts) and for awx-ha.  

Ever since then I get a weird api error400 on attempting to update the SCM project....it fails and despite finding somewhat similar use cases online I havent been able to get it work since.  I have tried modifying the roles/requirement yaml for projectinventory and also messed with rabbitMQ a bit.  

Have you seen this issue before.  It seems like a good feature I dont want to pass on

Luckily i had the api window still open when I got frustrated and decided to blow it all up again.

"    "detail": "null value in column \"job_tags\" violates not-null constraint\nDETAIL:  Failing row contains (6422, _68__azure_devops_git_repo, git, https://*************bjruyk5yei62e243ic6ku72oh**************@dev..., , t, f, null, 68, 0, check, , , null).\n""

**To Reproduce**
After installing awx on both nodes and running awx-ha scm projects refuse to update and throw a error 400

**Expected behavior**
For SCM projects ot update fine as before with no AWX-HA enabled.

**Additional context**
Error:     "detail": "null value in column \"job_tags\" violates not-null constraint\nDETAIL:  Failing row contains (6422, _68__azure_devops_git_repo, git, https://*************bjruyk5yei62e243ic6ku72oh**************@dev..., , t, f, null, 68, 0, check, , , null).\n"

**Comment by AechLyons** [comment]
I'm gonna take another crack at figuring it out now

**Comment by sujiar37** [comment]
@AechLyons , sorry for the late response. I wasn't able to re-produce such issues in SCM. Earlier, there was some issues with manual mode , however it has been fixed on this release. You could find more details here #18 

Have you had a chance to take a look on this [AWX-HA-Sandbox](https://github.com/sujiar37/AWX-HA-InstanceGroup/blob/master/sandbox.md)  and see if you can re-produce by following those instructions.
