### ISSUE TITLE
using single server for initial installation. and ran the command "ansible-playbook -i inventory/hosts awx_ha.yml" and error occurred near  "TASK [awx_ha : Build Docker Images in Primary Node] ". Please help.

### ISSUE THREAD

**Issue by sravany616** [sujiar37/AWX-HA-InstanceGroup#23]
TASK [awx_ha : Build Docker Images in Primary Node] *****************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: build() got an unexpected keyword argument 'stream'
failed: [server IP] (item={u'version': u'9.1.1', u'name': u'awx_web_ha', u'file': u'Dockerfile'}) => {"changed": false, "item": {"file": "Dockerfile", "name": "awx_web_ha", "version": "9.1.1"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_HZ1Q2e/ansible_module_docker_image.py\", line 602, in <module>\n    main()\n  File \"/tmp/ansible_HZ1Q2e/ansible_module_docker_image.py\", line 597, in main\n    ImageManager(client, results)\n  File \"/tmp/ansible_HZ1Q2e/ansible_module_docker_image.py\", line 295, in __init__\n    self.present()\n  File \"/tmp/ansible_HZ1Q2e/ansible_module_docker_image.py\", line 323, in present\n    self.results['image'] = self.build_image()\n  File \"/tmp/ansible_HZ1Q2e/ansible_module_docker_image.py\", line 520, in build_image\n    for line in self.client.build(**params):\nTypeError: build() got an unexpected keyword argument 'stream'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: build() got an unexpected keyword argument 'stream'
failed: [server IP] (item={u'version': u'9.1.1', u'name': u'awx_task_ha', u'file': u'Dockerfile.task'}) => {"changed": false, "item": {"file": "Dockerfile.task", "name": "awx_task_ha", "version": "9.1.1"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_CX43Mq/ansible_module_docker_image.py\", line 602, in <module>\n    main()\n  File \"/tmp/ansible_CX43Mq/ansible_module_docker_image.py\", line 597, in main\n    ImageManager(client, results)\n  File \"/tmp/ansible_CX43Mq/ansible_module_docker_image.py\", line 295, in __init__\n    self.present()\n  File \"/tmp/ansible_CX43Mq/ansible_module_docker_image.py\", line 323, in present\n    self.results['image'] = self.build_image()\n  File \"/tmp/ansible_CX43Mq/ansible_module_docker_image.py\", line 520, in build_image\n    for line in self.client.build(**params):\nTypeError: build() got an unexpected keyword argument 'stream'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by sujiar37** [comment]
@sravany616   Unfortunately, I couldn't reproduce this. Make sure that you have the right compose version is installed.
docker-compose==1.24.0

I had recommend you to try this [sandbox setup](https://github.com/sujiar37/AWX-HA-InstanceGroup/blob/master/sandbox.md) in a fresh box before deploying to any actual servers.

**Comment by crono782** [comment]
I have the exact same issue with same error message. Centos 7.7.1908 verified docker-compose 1.24.0.
