### ISSUE TITLE
Moving to Centos8 as base OS with python3

### ISSUE THREAD

**Issue by agougo** [sujiar37/AWX-HA-InstanceGroup#24]
Hello,

First of all thanks for the work that you have put into this. Starting ver 9.x.x the base OS for AWX was changed to centos8 with python3 as the standard interpreter. Are there any plans to move this to the new OS?

cheers

**Comment by sujiar37** [comment]
@agougo, thank you for reporting this. Since the new version (9.3.0) is out, I will test and release it out with the base OS as CentOS8 soon.
