### ISSUE TITLE
Enabling SSL functionality

### ISSUE THREAD

**Issue by dannyvanderaa** [sujiar37/AWX-HA-InstanceGroup#25]
Hi,

I would like to have the webinstances SSL enabled.
This seems not to be working.

Can you implement this as wel?

**Comment by Sreenadh8** [comment]
Hi @dannyvanderaa , I could able to do this with below method.. my setup on AWS environment, Put both web servers behind application load balancer and attach SSL Cert on LB level.  User your DNS/Route 53 for appropriate Host A records for accessing the url.


Regards,
Sreenadh
